"""HR self-service assistant with ONE Cedar-gated tool (AgentKit Identity homework).

The agent answers general HR questions for any authenticated user, but the
`get_payslip` tool is gated by an Agent Identity permission policy (Cedar):
before returning data, the tool asks the Identity PDP (CheckPermission)
whether the *verified caller* may invoke it. Result matrix:

    no / expired token   -> the runtime gateway (custom_jwt) rejects with 401
                            (locally: the entrypoint itself answers 401)
    alice (permitted)    -> tool runs, payslip returned (200)
    bob   (not in policy)-> chat works, tool returns 403 and the agent
                            explains the denial

Caller identity: the platform gateway strips the incoming Authorization header
after verifying it, so the entrypoint first looks for platform-forwarded
identity headers (whatever the gateway injects - logged on first call); if
none are present (local dev), it verifies the Bearer token itself against the
user pool's JWKS.
"""

import asyncio
import contextvars
import json
import os

from dotenv import load_dotenv

load_dotenv()
load_dotenv(".env.identity")  # generated by setup_identity.py (git-ignored)

# Corp-VPN TLS interception: trust the OS store (same fix as the other samples).
if os.getenv("DISABLE_TRUSTSTORE", "0") != "1":
    try:
        import truststore

        truststore.inject_into_ssl()
    except ImportError:
        pass

from agentkit.apps import AgentkitSimpleApp  # noqa: E402
from veadk import Agent, Runner  # noqa: E402

from identity_utils import PoolJwtVerifier, check_permission  # noqa: E402

# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------

PERMISSION_NAMESPACE = os.getenv("PERMISSION_NAMESPACE", "payslip-hw")
TOOL_RESOURCE_ID = "get_payslip"

_discovery_url = os.getenv("IDENTITY_DISCOVERY_URL", "")
_allowed_clients = [
    c.strip() for c in os.getenv("IDENTITY_ALLOWED_CLIENTS", "").split(",") if c.strip()
]
_verifier = (
    PoolJwtVerifier(_discovery_url, _allowed_clients)
    if _discovery_url and _allowed_clients
    else None
)

# Verified claims of the current caller, set by the entrypoint per request.
CALLER_CLAIMS: contextvars.ContextVar[dict] = contextvars.ContextVar(
    "caller_claims", default={}
)

# --------------------------------------------------------------------------
# Mock payroll data (the "business system" the tool fronts)
# --------------------------------------------------------------------------

PAYSLIPS = {
    "E1001": {"name": "Chen Wei", "role": "Senior Backend Engineer",
              "base": 9800, "bonus": 1200, "tax": 1540},
    "E1002": {"name": "Priya Nair", "role": "Product Manager",
              "base": 10500, "bonus": 800, "tax": 1695},
    "E1003": {"name": "Marcus Lim", "role": "UX Designer",
              "base": 8200, "bonus": 500, "tax": 1222},
}
CURRENCY = "SGD"
PERIOD = "2026-07"


# --------------------------------------------------------------------------
# The one tool - Cedar-gated
# --------------------------------------------------------------------------

async def get_payslip(employee_id: str) -> dict:
    """Look up an employee's payslip for the current pay period.

    Access is controlled by an Agent Identity permission policy: only callers
    explicitly permitted in the policy may use this tool.

    Args:
        employee_id: Company employee ID, e.g. "E1001".

    Returns:
        A dict with status 200 + payslip fields, 403 when the caller is not
        permitted, 404 for an unknown employee, 401 when the caller identity
        is missing.
    """
    claims = CALLER_CLAIMS.get()
    sub = claims.get("sub", "")
    if not sub:
        return {
            "status": 401,
            "error": "unauthorized",
            "message": "No verified caller identity - log in first.",
        }

    allowed = await asyncio.to_thread(
        check_permission,
        namespace=PERMISSION_NAMESPACE,
        principal_id=sub,
        resource_id=TOOL_RESOURCE_ID,
    )
    if not allowed:
        return {
            "status": 403,
            "error": "forbidden",
            "message": (
                f"Caller '{claims.get('username') or claims.get('email') or sub}' "
                f"is not permitted to invoke {TOOL_RESOURCE_ID} "
                f"(namespace {PERMISSION_NAMESPACE})."
            ),
        }

    record = PAYSLIPS.get(employee_id.upper())
    if not record:
        return {
            "status": 404,
            "error": "not_found",
            "message": f"No employee with ID {employee_id!r}.",
        }
    return {
        "status": 200,
        "employee_id": employee_id.upper(),
        "period": PERIOD,
        "currency": CURRENCY,
        **record,
        "net": record["base"] + record["bonus"] - record["tax"],
    }


# --------------------------------------------------------------------------
# Caller identity extraction
# --------------------------------------------------------------------------

# Header names the platform gateway might inject after verifying the JWT
# (discovered by logging - see entrypoint). Extend when known.
_FORWARDED_SUB_HEADERS = (
    "x-user-sub",
    "x-verified-sub",
    "x-auth-sub",
    "x-authenticated-user",
    "x-consumer-username",
)


def _extract_caller_claims(headers: dict) -> dict:
    """Who is calling? Platform-forwarded identity first, JWKS fallback second."""
    normalized = {str(k).lower(): v for k, v in (headers or {}).items()}
    print(f"[identity] inbound headers: {sorted(normalized)}")

    for name in _FORWARDED_SUB_HEADERS:
        if normalized.get(name):
            print(f"[identity] using platform-forwarded identity header {name}")
            return {"sub": normalized[name], "via": name}

    auth = normalized.get("authorization", "")
    if auth.startswith("Bearer ") and _verifier:
        token = auth.removeprefix("Bearer ").strip()
        try:
            claims = _verifier.verify(token)
            claims["via"] = "jwks-self-verify"
            return claims
        except Exception as exc:
            print(f"[identity] Bearer token verification failed: {exc}")
            return {}
    return {}


# --------------------------------------------------------------------------
# Agent + app
# --------------------------------------------------------------------------

INSTRUCTION = """You are an HR self-service assistant for a company.

You may answer general HR-policy questions conversationally, and you have
exactly one system tool: get_payslip(employee_id), which returns an employee's
payslip for the current pay period.

Rules:
- ALWAYS call the tool for payslip data. Never invent or estimate figures.
- If the tool returns status 403, politely explain that the caller does not
  have permission to view payslips and should contact the HR administrator
  for access. Do not retry.
- If it returns 404, say the employee ID is unknown.
- On success, present the payslip clearly: name, role, period, base, bonus,
  tax, and net pay with the currency.
"""

agent = Agent(
    model_name=os.getenv("MODEL_NAME", "deepseek-v4-pro-ga-260813"),
    instruction=INSTRUCTION,
    tools=[get_payslip],
)
runner = Runner(agent=agent)

app = AgentkitSimpleApp()


@app.entrypoint
async def run(payload: dict, headers: dict) -> str:
    prompt = (payload or {}).get("prompt")
    if not prompt:
        return json.dumps({"status": 400, "error": "missing 'prompt' in payload"})

    claims = _extract_caller_claims(headers)
    if not claims.get("sub"):
        # Behind the platform gateway this is unreachable (it 401s first);
        # locally this is what rows 1-2 of the demo matrix hit.
        return json.dumps(
            {
                "status": 401,
                "error": "unauthorized",
                "message": "A valid user-pool Bearer token is required.",
            }
        )
    CALLER_CLAIMS.set(claims)
    print(f"[identity] caller sub={claims.get('sub')} via={claims.get('via')}")

    response = await runner.run(
        messages=prompt,
        user_id=claims.get("sub", "user"),
        session_id=(payload or {}).get("session_id", "default"),
    )
    return response


@app.ping
def ping() -> str:
    return "pong!"


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", "8000")))
