"""Provision everything the payslip homework needs on BytePlus Agent Identity.

Idempotent: safe to re-run; existing pool/client/users/namespace/policy are
reused. Passwords and IDs are stored in `.env.identity` (git-ignored) so
re-runs and the demo script can pick them up.

Creates / verifies:
  1. User pool `payslip-hw-pool`
  2. App client `payslip-hw-client` (normal token lifetime) and
     `payslip-hw-shortlived` (id_token life_time_seconds = 60, for the
     expired-token demo row)
  3. Users `alice` (will be permitted) and `bob` (not permitted), CONFIRMED
  4. Permission namespace `payslip-hw`
  5. A Cedar policy permitting alice to invoke Tool::"get_payslip"
  6. Smoke check: CheckPermission(alice) == True, CheckPermission(bob) == False

Usage:
    set -a && source .env && set +a        # BYTEPLUS_ACCESS_KEY / SECRET_KEY
    python setup_identity.py
"""

from __future__ import annotations

import os
import sys
import time

from dotenv import load_dotenv

load_dotenv()
# Reusable values from a previous run (passwords, ids) - git-ignored.
load_dotenv(".env.identity")

from identity_utils import (  # noqa: E402
    check_permission,
    decode_jwt_payload,
    discovery_url_for,
    generate_password,
    id_api_client,
    initiate_auth,
)

POOL_NAME = os.getenv("USER_POOL_NAME", "payslip-hw-pool")
CLIENT_NAME = os.getenv("USER_POOL_CLIENT_NAME", "payslip-hw-client")
SHORT_CLIENT_NAME = "payslip-hw-shortlived"
NAMESPACE = os.getenv("PERMISSION_NAMESPACE", "payslip-hw")
POLICY_NAME = "alice-may-read-payslips"
TOOL_RESOURCE_ID = "get_payslip"
SHORT_TTL_SECONDS = 60

# Cedar entity types must match the Type fields sent in the CheckPermission
# request VERBATIM (verified against the live PDP by probe_permission.py):
# identity_utils.check_permission sends Type="user"/"action"/"tool", so the
# policy uses user::/action::/tool:: - all lowercase. The console docs show
# Action:: capitalized because the Permission Gateway PEP sends Type="Action".
CEDAR_POLICY_TEMPLATE = """permit(
    principal == user::"{principal}",
    action == action::"invoke",
    resource == tool::"get_payslip"
);"""

_env_lines: dict[str, str] = {}


def remember(key: str, value: str) -> None:
    _env_lines[key] = value


def save_env_identity() -> None:
    with open(".env.identity", "w") as fh:
        fh.write("# Generated by setup_identity.py - git-ignored, contains secrets\n")
        for key, value in _env_lines.items():
            fh.write(f"{key}={value}\n")
    print(f"\nWrote .env.identity ({len(_env_lines)} values)")


def find_or_create_pool(client) -> str:
    import byteplussdkid

    resp = client.list_user_pools(
        byteplussdkid.ListUserPoolsRequest(
            filter={"Name": POOL_NAME}, page_number=1, page_size=1
        )
    )
    if resp.data:
        pool_id = resp.data[0].uid
        print(f"User pool exists: {POOL_NAME} ({pool_id})")
        return pool_id
    created = client.create_user_pool(
        byteplussdkid.CreateUserPoolRequest(name=POOL_NAME)
    )
    print(f"Created user pool: {POOL_NAME} ({created.uid})")
    return created.uid


def find_or_create_client(client, pool_id: str, name: str) -> tuple[str, str]:
    import byteplussdkid

    resp = client.list_user_pool_clients(
        byteplussdkid.ListUserPoolClientsRequest(
            filter={"Name": name}, page_number=1, page_size=1, user_pool_uid=pool_id
        )
    )
    if resp.data:
        client_uid = resp.data[0].uid
        got = client.get_user_pool_client(
            byteplussdkid.GetUserPoolClientRequest(
                user_pool_uid=pool_id, client_uid=client_uid
            )
        )
        print(f"Client exists: {name} ({client_uid})")
        return client_uid, got.client_secret
    created = client.create_user_pool_client(
        byteplussdkid.CreateUserPoolClientRequest(
            user_pool_uid=pool_id, client_type="WEB_APPLICATION", name=name
        )
    )
    print(f"Created client: {name} ({created.uid})")
    return created.uid, created.client_secret


def set_id_token_ttl(client, pool_id: str, client_uid: str, seconds: int) -> None:
    import byteplussdkid

    client.update_user_pool_client(
        byteplussdkid.UpdateUserPoolClientRequest(
            user_pool_uid=pool_id,
            client_uid=client_uid,
            id_token={"LifeTimeSeconds": seconds},
        )
    )
    print(f"Set id_token lifetime of {client_uid} to {seconds}s")


def find_or_create_user(
    client, pool_id: str, username: str, password: str
) -> str:
    import byteplussdkid

    resp = client.list_users(
        byteplussdkid.ListUsersRequest(
            user_pool_uid=pool_id,
            page_number=1,
            page_size=1,
            filter={"PreferredUsername": username},
        )
    )
    if resp.data:
        user_uid = resp.data[0].uid
        # Make re-runs deterministic: force the password to the stored one.
        client.update_user(
            byteplussdkid.UpdateUserRequest(
                user_pool_uid=pool_id, user_uid=user_uid, password=password
            )
        )
        print(f"User exists: {username} ({user_uid}); password refreshed")
    else:
        created = client.create_user(
            byteplussdkid.CreateUserRequest(
                user_pool_uid=pool_id,
                email=f"{username}@example.com",
                preferred_username=username,
                password=password,
            )
        )
        user_uid = created.uid
        print(f"Created user: {username} ({user_uid})")
    client.update_user(
        byteplussdkid.UpdateUserRequest(
            user_pool_uid=pool_id, user_uid=user_uid, user_state="CONFIRMED"
        )
    )
    return user_uid


def find_or_create_namespace(client) -> None:
    import byteplussdkid

    resp = client.list_namespaces(
        byteplussdkid.ListNamespacesRequest(page_number=1, page_size=100)
    )
    for item in getattr(resp, "namespaces", []) or []:
        if getattr(item, "namespace_name", None) == NAMESPACE:
            print(f"Namespace exists: {NAMESPACE}")
            return
    try:
        client.create_namespace(
            byteplussdkid.CreateNamespaceRequest(
                namespace_name=NAMESPACE,
                description="Payslip homework permission space",
            )
        )
    except Exception as exc:
        if "AlreadyExists" not in str(exc):
            raise
        print(f"Namespace exists: {NAMESPACE}")
        return
    print(f"Created namespace: {NAMESPACE}")


def policy_exists(client) -> bool:
    import byteplussdkid

    try:
        client.get_policy(
            byteplussdkid.GetPolicyRequest(
                namespace_name=NAMESPACE, policy_name=POLICY_NAME
            )
        )
        return True
    except Exception:
        return False


def create_policy(client, alice_sub: str) -> None:
    """Cedar permit: alice may invoke Tool::get_payslip. Fallback: GrantPermission."""
    import byteplussdkid

    if policy_exists(client):
        # Recreate: the desired Cedar text may have changed between runs.
        client.delete_policy(
            byteplussdkid.DeletePolicyRequest(
                namespace_name=NAMESPACE, policy_name=POLICY_NAME
            )
        )
        print(f"Deleted existing policy {POLICY_NAME} (recreating with current template)")

    cedar = CEDAR_POLICY_TEMPLATE.format(principal=alice_sub)
    try:
        client.create_policy(
            byteplussdkid.CreatePolicyRequest(
                namespace_name=NAMESPACE,
                policy_name=POLICY_NAME,
                policy=cedar,
                description="alice (HR) may invoke get_payslip",
            )
        )
        print(f"Created Cedar policy {POLICY_NAME}:\n{cedar}")
        return
    except Exception as exc:
        print(f"create_policy rejected the Cedar text ({exc}); trying GrantPermission")

    client.grant_permission(
        byteplussdkid.GrantPermissionRequest(
            namespace_name=NAMESPACE,
            policy_name=POLICY_NAME,
            effect="Allow",
            description="alice (HR) may invoke get_payslip",
            principal={"Type": "user", "Id": alice_sub},
            operation={"Type": "action", "Id": "invoke"},
            resource={"Type": "tool", "Id": TOOL_RESOURCE_ID},
        )
    )
    print(f"Granted permission via GrantPermission as {POLICY_NAME}")


def main() -> int:
    client = id_api_client()

    print("== 1. user pool ==")
    pool_id = find_or_create_pool(client)
    remember("IDENTITY_POOL_ID", pool_id)
    remember("IDENTITY_DISCOVERY_URL", discovery_url_for(pool_id))

    print("\n== 2. app clients ==")
    client_id, client_secret = find_or_create_client(client, pool_id, CLIENT_NAME)
    remember("IDENTITY_CLIENT_ID", client_id)
    remember("IDENTITY_CLIENT_SECRET", client_secret)
    short_id, short_secret = find_or_create_client(client, pool_id, SHORT_CLIENT_NAME)
    remember("IDENTITY_SHORTLIVED_CLIENT_ID", short_id)
    remember("IDENTITY_SHORTLIVED_CLIENT_SECRET", short_secret)
    try:
        set_id_token_ttl(client, pool_id, short_id, SHORT_TTL_SECONDS)
    except Exception as exc:
        print(f"Could not set short TTL ({exc}) - expired-token row needs a wait")

    print("\n== 3. users ==")
    alice_pwd = os.getenv("ALICE_PASSWORD") or generate_password()
    bob_pwd = os.getenv("BOB_PASSWORD") or generate_password()
    alice_uid = find_or_create_user(client, pool_id, "alice", alice_pwd)
    bob_uid = find_or_create_user(client, pool_id, "bob", bob_pwd)
    remember("ALICE_PASSWORD", alice_pwd)
    remember("BOB_PASSWORD", bob_pwd)
    remember("ALICE_UID", alice_uid)
    remember("BOB_UID", bob_uid)

    print("\n== 4. tokens (to learn each user's sub) ==")
    alice_auth = initiate_auth(
        pool_id=pool_id, client_id=client_id,
        username="alice", password=alice_pwd, client_secret=client_secret,
    )
    bob_auth = initiate_auth(
        pool_id=pool_id, client_id=client_id,
        username="bob", password=bob_pwd, client_secret=client_secret,
    )
    alice_claims = decode_jwt_payload(alice_auth.get("IdToken", ""))
    bob_claims = decode_jwt_payload(bob_auth.get("IdToken", ""))
    alice_sub = alice_claims.get("sub", alice_uid)
    bob_sub = bob_claims.get("sub", bob_uid)
    print(f"alice: uid={alice_uid} sub={alice_sub}")
    print(f"  id_token expires in {alice_auth.get('ExpiresIn')}s")
    print(f"bob:   uid={bob_uid} sub={bob_sub}")
    remember("ALICE_SUB", alice_sub)
    remember("BOB_SUB", bob_sub)

    print("\n== 5. permission namespace + Cedar policy ==")
    find_or_create_namespace(client)
    create_policy(client, alice_sub)
    remember("PERMISSION_NAMESPACE", NAMESPACE)

    # Persist everything BEFORE the smoke check: the pool/clients/users are
    # real even if the policy dialect turns out wrong, and demo.py +
    # probe_permission.py both read this file.
    remember(
        "IDENTITY_ALLOWED_CLIENTS",
        ",".join([client_id, short_id]),
    )
    save_env_identity()

    print("\n== 6. smoke check against the Cedar PDP ==")
    alice_ok = check_permission(
        namespace=NAMESPACE, principal_id=alice_sub, resource_id=TOOL_RESOURCE_ID
    )
    time.sleep(1)
    bob_ok = check_permission(
        namespace=NAMESPACE, principal_id=bob_sub, resource_id=TOOL_RESOURCE_ID
    )
    print(f"\nalice allowed: {alice_ok} (expect True)")
    print(f"bob allowed:   {bob_ok} (expect False)")
    if not alice_ok or bob_ok:
        print("SMOKE CHECK FAILED - inspect the policy in the Identity console,")
        print("or run probe_permission.py to try other Cedar dialects.")
        return 1

    print("\nSetup complete. Next: run the agent locally, then demo.py.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
